server:
  port : 8080
spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**
        - id: veterinaries
          predicates:
            - Path=/veterinaries/**
          uri: http://localhost:8081
        - id : visits-server
          predicates:
            - Path=/visits/**
          uri: http://localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/